### ISSUE TITLE
repo status?

### ISSUE THREAD

**Issue by mrose17** [jasontbradshaw/irobot#1]
hi. i am getting ready to integrate with a roomba wifi module -- http://www.roowifi.com

before i dig in, i just wanted to check the status of this repo. my plan is to submit pull requests to you with the additional support.

thanks!

**Comment by jasontbradshaw** [comment]
I started this for a telepresence project I've been working on, but haven't actually used it in production yet! I would consider it safe to use, but since it hasn't been battle-hardened yet, I'm sure there are random bugs lurking in the corners.

My concern is whether integrating this module really fits with the spirit of this project. I'm not entirely opposed, but I would need some convincing to say "go for it". My initial reaction is that it might be a better fit for its own project (or fork), since it seems like, from my cursory reading of the user manual, that the RooWifi basically duplicates all that this library does, though a different interface.

**Comment by mrose17** [comment]
thanks for the reply!

all, i'm thinking of doing is doing is letting the user pass a socket descriptor instead of a device path. probably a 30 line diff.

i'm going to try plugging in the roowifi today to see how it looks and will report back.

many thanks!

**Comment by jasontbradshaw** [comment]
If it's something elegant like that, I'm on board!
