### ISSUE TITLE
FYI: current status

### ISSUE THREAD

**Issue by mrose17** [jasontbradshaw/irobot#2]
i did an initial check-in for RooWiFi support: https://github.com/TheThingSystem/irobot/commit/c243da5f2e2671a662858479271f432183af6cff

i won't submit a request for a while, since i still need to test. a few things i've found:
1. at present, the RooWiFi is the only commercial solution, although there's a project on indiegogo, that sadly probably won't meet it's funding goal. sigh.
2. i have done my best to minimize changes to your code (which, by the way, is very clean). however, you might think i've changed a bit much.
3. i am pretty sure that future Wi-Fi solutions for the Roomba will be bi-directional; so this is the code that got added to robot.js; however, the RooWiFi is unidirectional in the sense that it doesn't return sensor data over the same TCP connection that you send commands on. instead, you're expected to get a json file via http. and, to make things more complex, you can have only one socket open at a time to the RooWiFi.

so, the RooWifi-specific code is in a new file. if someone else wants to integrate a network solution that is actually bi-directional, then they won't need the file.
1. question: do you have an iRobot create? if so, is there a DIN serial connector on it somewhere? i haven't been able to find a picture with enough detail to know one way or the other…

thanks!

**Comment by jasontbradshaw** [comment]
I do have a Create, and that's what precipitated this project!

It has a single mini-DIN female serial port, which you can see on page 5 of the [user manual](http://www.irobot.com/filelibrary/create/Create%20Manual_Final.pdf) and page 4 of the [Open Interface manual](http://www.irobot.com/filelibrary/pdfs/hrd/create/Create%20Open%20Interface_v2.pdf).

I think the OI manual also describes how you can interface via the large serial connector in the cargo bay, but I just used the included mini-DIN to serial adapter that comes with the Create.

As far as the code goes, it looks pretty good, especially the addition of command 'sets' for the different series/types of robot. I am concerned that it puts a large onus on the user to figure out which particular things to pass in to the constructor to get it to work. The `sendcommand` override, for instance, is non-obvious.

To clean things up a bit more and make it more extensible for future devices like the RooWifi, it might make sense to refactor command sending and sensor data receiving into some sort of `Adapter` class. In my vision, there would be a `SerialPortAdapter` and a `RooWifiAdapter`, and you would pass a configured instance of one of these into the `Robot` constructor. Each `Adapter` would have a `sendCommand` method that subscribes to the open interface spec, and would emit `sensordata` events in the format that they're currently parsed into by the `prettifySensorData` method. It could also have a `supportsFeature` method that could detect differences like the non-support of the Demo command, for instance.

This would make it easier to encapsulate all the protocol-specific code that's currently build into the `Robot` class. Luckily, since the `SerialPort` library does pretty much everything through events (which is what `Robot` expects to receive), it shouldn't be too hard to abstract it into an event-emitting `Adapter` class.

Thoughts?

**Comment by mrose17** [comment]
thanks for the note.

great, i'll get a Create. what accessories do you suggest i get?

i agree with your comment on sendcommand, although i was intending it to be something the user doesn't mess with (only those maintainers of the package). i suspect adding some things to the README would help. let me try my hand at that.

i agree we need something like _supportsFeature_, i need to think a bit about the refactoring.

i'm not sure whether the roowifi support will be a "one off" or the harbinger of things to come. the limitations are somewhat annoying. right now i'm getting ready to put together a beaglebone black with a wifi adapter that i will try connect with a mini-DIN - my goal is to have it run a node.js program that is totally transparent (none of this business about juggling too connections), and it can announce itself via mDNS, etc., etc.

anyway, let me do a bit of work, and i'll circle back to you…
- marshall

ps: this is a nice package, thanks!

**Comment by jasontbradshaw** [comment]
I got the Create off of ebay relatively cheaply (~$70). Additionally, I bought a charger cord, rechargeable battery, and home base:

http://www.amazon.com/gp/product/B0027BNEYO/ref=wms_ohs_product?ie=UTF8&psc=1
http://www.amazon.com/gp/product/B004KNO59K/ref=wms_ohs_product?ie=UTF8&psc=1
http://www.amazon.com/gp/product/B00022HZ0O/ref=wms_ohs_product?ie=UTF8&psc=1

I haven't tested the docking with the home base yet, but I can attest that it successfully charges from it, at least. The rechargeable battery is necessary if you just buy the Create alone, since it doesn't come with one otherwise.

I also bought a Raspberry Pi to use as it's "brain", and power it off the Create's internal battery. I opened the Create up (you need small-ish Phillips head screwdrivers to do so) and tapped directly into the battery leads, then fed the two wires back out through a hole I drilled in the case in the cargo bay. I connected them to one of [these](http://www.amazon.com/gp/product/B008BHB4L8/ref=wms_ohs_product?ie=UTF8&psc=1), which does an admirable job of stepping down the 16.6v battery voltage to a configurable voltage.

I hacked up a [powered USB hub](http://www.amazon.com/gp/product/B005P2BY5I/ref=wms_ohs_product?ie=UTF8&psc=1) and basically replaced its wall wart with the voltage converter output. The Pi draws power off of this with no problems, and it allows me to use the remaining USB sockets to power other things in the future (I'm making a telepresence robot, so a tablet and speakers). A USB-to-serial adapter lets the Pi communicate with the Create, rounding out the experience.

And thanks! I found all the other libraries lacking/poorly-designed, so I tried my hand at it over a couple of weekends. I'm glad it's of use to someone else besides myself!

**Comment by mrose17** [comment]
i took a few rough edges off the code and did another commit https://github.com/TheThingSystem/irobot/commit/92f2e9c4082a69dba8a82b915baf71087bd0e8e9

the README is now more informative, and i think we can decide what additional commands need to be added and/or documented (-;

it sounds like you're doing the same thing with the RPi that i'd like to do with the BBB. which USB-to-serial adapter did you use to attach the RPI's USB port to the Create's DIN port.

in terms of usage: i'm one of the curators for the #thingsystem -- an open source autonomy server-- so my goal is to get this integrated so you can do things like "when the motion sensor on the door reports someone's knocking then send the telepresence robot over to the window next to the door to take a look, and while you're at it, you might as well do a push notification and turn on the light over the door and …"

many thanks!

**Comment by jasontbradshaw** [comment]
I don't remember which USB-serial adapter I used; I picked it up at a local store some years ago. I wager any would do, though - Ubuntu picked it up with no problems at all.

**Comment by mrose17** [comment]
no worries… so, where we are now is this: i'm still testing with the RooWifi. i also have a BBB up and running on wifi and am exploring how best to connect to (and power it from) an iRobot device. more details soon (i hope!)
